---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  pull-requests: read
  packages: read
  security-events: write

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/app-ci.yaml@6fd809e6e18800706d6efae8e8fa2995872adc42 # v1.1.1
