---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions: {}

jobs:
  ci:
    permissions:
      actions: read
      contents: write
      pull-requests: read
      packages: read
      security-events: write
    uses: erik73/workflows/.github/workflows/app-ci.yaml@8926a2fe9a9cff77c286ba9853fd9d87ecb0c616 # v2.0.0

  deploy:
    needs: ci
    permissions:
      contents: read
      packages: write
    uses: erik73/workflows/.github/workflows/app-deploy.yaml@8926a2fe9a9cff77c286ba9853fd9d87ecb0c616 # v2.0.0
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
