---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/labels.yaml@8926a2fe9a9cff77c286ba9853fd9d87ecb0c616 # v2.0.0
