---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/labels.yaml@6fd809e6e18800706d6efae8e8fa2995872adc42 # v1.1.1
