---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/pr-labels.yaml@8926a2fe9a9cff77c286ba9853fd9d87ecb0c616 # v2.0.0
