---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/stale.yaml@8926a2fe9a9cff77c286ba9853fd9d87ecb0c616 # v2.0.0
